=== AchrafAmil/checkstyle/src/checkstyle/com/puppycrawl/tools/checkstyle/checks/imports/import_control_1_0.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT import-control ((allow|disallow)*,subpackage*)>

<!ATTLIST import-control
  pkg NMTOKEN #REQUIRED>

<!ELEMENT subpackage ((allow|disallow)*,subpackage*)>

<!ATTLIST subpackage
  name NMTOKEN #REQUIRED>

<!ELEMENT allow EMPTY>

<!ATTLIST allow
  pkg NMTOKEN #REQUIRED>

<!ELEMENT disallow EMPTY>

<!ATTLIST disallow
  pkg NMTOKEN #REQUIRED>

=== AchrafAmil/checkstyle/import-control.xml
<?xml version="1.0"?>
<!DOCTYPE import-control PUBLIC
    "-//Puppy Crawl//DTD Import Control 1.0//EN"
    "http://www.puppycrawl.com/dtds/import_control_1_0.dtd">

<import-control pkg="com.puppycrawl.tools.checkstyle">

  <allow pkg="antlr"/>
  <allow pkg="com.puppycrawl.tools.checkstyle.api"/>
  <allow pkg="java.io"/>
  <allow pkg="java.net"/>
  <allow pkg="java.util"/>
  <allow pkg="javax.xml.parsers"/>
  <allow pkg="org.apache.commons.beanutils"/>
  <allow pkg="org.apache.commons.logging"/>
  <allow pkg="org.xml.sax"/>

  <!-- The local ones -->
  <allow pkg="com.puppycrawl.tools.checkstyle.grammars" local-only="selected"/>
  <allow class="java.security.MessageDigest" local-only="selected"/>
  <allow pkg="org.apache.commons.cli" local-only="selected"/>
  <allow pkg="org.apache.tools.ant" local-only="selected"/>

  <subpackage name="api">
    <allow pkg="java.beans"/>
    <allow pkg="java.lang.reflect"/>
    <allow pkg="java.text"/>
    <allow class="com.puppycrawl.tools.checkstyle.grammars.CommentListener"
           local-only="selected"/>
    <allow class="com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaTokenTypes"
           local-only="selected"/>
  </subpackage>

  <subpackage name="checks">
    <allow pkg="com.puppycrawl.tools.checkstyle.checks"/>

    <subpackage name="indentation">
      <allow pkg="java.lang.reflect"/>
      <allow pkg="org.apache.commons.collections"/>
    </subpackage>

  </subpackage>

  <subpackage name="doclets">
    <allow pkg="com.sun.javadoc"/>
  </subpackage>

  <subpackage name="filters">
    <allow pkg="java.lang.ref"/>
  </subpackage>

  <subpackage name="gui">
    <allow pkg="java.awt"/>
    <allow pkg="javax.swing"/>
  </subpackage>
</import-control>
